#!/bin/sh

LOG_FILE=$(dirname $0)/logs/timecockpit-commits.csv

if [ ! -s $LOG_FILE ]
then
	# echo "Creating time cockpit logfile in CSV format"
	echo "Id;EventTime;ChangeSetComment;Changes;Notes;Finalized" > $LOG_FILE
fi

REPO="$(basename `git rev-parse --show-toplevel`)"
BRANCH="$(git branch --show-current)"
INDEX_FILES="$(git diff --cached --name-status)"
COMMIT_MSG="$(cat $1)"

echo "\"1\";\"$(date '+%Y-%m-%d %H:%M:%S')\";\"${REPO} ${BRANCH}\";\"${COMMIT_MSG}\";\"${INDEX_FILES}\";\"true\" " >> $LOG_FILE

exit 0